import Link from "next/link";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by exgoya",
};

export default async function WorkLayout({ children }) {

  const resp1 = await fetch(process.env.NEXT_PUBLIC_BACKEND_API_URL+"api");
  const data1 = await resp1.json();
  return (
    <html>
      <body>
        <h1>{data1.message}</h1>
        <h1><Link href="/">WEB</Link></h1>
        {children}
      </body>
    </html>
  );
}